// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7TCcWzfFMAGcG18iNT3t9b
// Component: 4zC7PBjRS1TV

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: ecTbNI-neECJ/component
import { AntdAccordion } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import { accordionHelpers as AntdAccordion_Helpers } from "@plasmicpkgs/antd5/skinny/registerCollapse";
import { AntdAccordionItem } from "@plasmicpkgs/antd5/skinny/registerCollapse";

import { useScreenVariants as useScreenVariantsg8CwaMuNk6Bl } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: G8CWAMuNk6bl/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 7TCcWzfFMAGcG18iNT3t9b/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 4zC7PBjRS1TV/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: harcokY7B7he/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: 6C8_QJjInsT8/icon
import FacebookSvgIcon from "./icons/PlasmicIcon__FacebookSvg"; // plasmic-import: m99uKwoUipaq/icon
import InstagramSvgIcon from "./icons/PlasmicIcon__InstagramSvg"; // plasmic-import: 7YmuCeLQ6ncY/icon
import TwitterSvgIcon from "./icons/PlasmicIcon__TwitterSvg"; // plasmic-import: xjTv-XmyiYf9/icon
import LinkedInSvgIcon from "./icons/PlasmicIcon__LinkedInSvg"; // plasmic-import: sz1c4bc0uGLg/icon

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  accordion?: Flex__<typeof AntdAccordion>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "accordion.activePanelId",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec(
          "activePanelId",
          AntdAccordion_Helpers
        )
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsg8CwaMuNk6Bl()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <section className={classNames(projectcss.all, sty.section__pXgwT)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__wJ0J6)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__qVtQ)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ncOac)}
                  displayHeight={"40px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"233px"}
                  src={{
                    src: "/plasmic/next_step_code_landing/images/group1487663536Svg.svg",
                    fullWidth: 251,
                    fullHeight: 41,
                    aspectRatio: 6.121951
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__jyxGa)}
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__vpna2)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__kEn02)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__vb6)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__llFay
                      )}
                    >
                      {"Our Story"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button___6IbMu)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg___47B4V)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__xl1Od)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dX9W
                      )}
                    >
                      {"Projects"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__l1D09)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__eamf2)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__sv7Zh)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3XS6
                      )}
                    >
                      {"Contact"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__nKqqm)}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__n7Tzg)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__bl6Aw)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gBjV
                      )}
                    >
                      {"Book a Call"}
                    </div>
                  </Button>
                </Stack__>
                {false ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7HrZ)}
                  >
                    <button
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        projectcss.__wab_text,
                        sty.button___3A0Fd
                      )}
                    >
                      {"Sign up"}
                    </button>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__sCh6Z
                      )}
                      color={"clear"}
                      endIcon={
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__nibzZ)}
                          role={"img"}
                        />
                      }
                      startIcon={
                        <CheckSvgIcon
                          className={classNames(projectcss.all, sty.svg__cGmVl)}
                          role={"img"}
                        />
                      }
                      submitsForm={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uctbA
                        )}
                      >
                        {"Log in"}
                      </div>
                    </Button>
                  </div>
                ) : null}
              </Stack__>
            </Stack__>
            <div className={classNames(projectcss.all, sty.columns___99OJ)}>
              <div className={classNames(projectcss.all, sty.column___0KRn8)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__exDL
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#A8FF00" }}
                    >
                      {"Launch Online."}
                    </span>
                    <React.Fragment>{"\n"}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#FFFFFF" }}
                    >
                      {"Effortlessly and Professionally."}
                    </span>
                  </React.Fragment>
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__o41NO
                  )}
                >
                  {
                    "Get your business online quickly with a custom-built website and ongoing support for growth."
                  }
                </div>
                <Button
                  className={classNames("__wab_instance", sty.button__o1WUl)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__w9GEy
                    )}
                  >
                    {"Schedule a Call"}
                  </div>
                </Button>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__wi8L7)}>
            <div className={classNames(projectcss.all, sty.columns__fBsHh)}>
              <div className={classNames(projectcss.all, sty.column__b3AQg)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__j80H
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#FFFFFF" }}
                    >
                      {"What our "}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#A8FF00" }}
                    >
                      {"satisfied client say"}
                    </span>
                  </React.Fragment>
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__upia
                  )}
                >
                  {
                    "Get your business online quickly with a custom-built website and ongoing support for growth."
                  }
                </div>
                <div className={classNames(projectcss.all, sty.columns__r9Io2)}>
                  <div
                    className={classNames(projectcss.all, sty.column__uhd2J)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__poLhD)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/next_step_code_landing/images/cardPng.png",
                        fullWidth: 1920,
                        fullHeight: 880,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div className={classNames(projectcss.all, sty.column__r7Bo)}>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__m79Tp)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/next_step_code_landing/images/cardPng.png",
                        fullWidth: 1920,
                        fullHeight: 880,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__rpN01)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__zQjof)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/next_step_code_landing/images/cardPng.png",
                        fullWidth: 1920,
                        fullHeight: 880,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__kxlzy)}>
            <div className={classNames(projectcss.all, sty.columns__xFdUw)}>
              <div className={classNames(projectcss.all, sty.column__accnB)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__h6674)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__tALfR
                    )}
                  >
                    {"DEVELOPMENT"}
                  </h1>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1___9D9
                    )}
                  >
                    {"OPTIMIZATION"}
                  </h1>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__hu0Bi
                    )}
                  >
                    {"BRANDING"}
                  </h1>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__zt4X5
                    )}
                  >
                    {"COPYWRITING"}
                  </h1>
                </Stack__>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section___5Eq9B)}>
            <div className={classNames(projectcss.all, sty.columns__wbnFl)}>
              <div className={classNames(projectcss.all, sty.column__u6Gei)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1___51U88
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#A8FF00" }}
                    >
                      {"Your Complete Digital Presence "}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#FFFFFF" }}
                    >
                      {"For One Simple Charge"}
                    </span>
                  </React.Fragment>
                </h1>
                <div className={classNames(projectcss.all, sty.columns__otRqY)}>
                  <div
                    className={classNames(projectcss.all, sty.column___4ByGd)}
                  >
                    <section
                      className={classNames(projectcss.all, sty.section__qmYI)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__o7ZqP
                        )}
                      >
                        {"Design. Develop. Brand. Write."}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__akD3B
                        )}
                      >
                        {
                          "We offer everything you need to launch and grow your business online\u2014all for just $1000."
                        }
                      </div>
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__uAtua
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zn63Z
                          )}
                        >
                          {"Schedule a Call"}
                        </div>
                      </Button>
                    </section>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__ll1O3)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___0MinK)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/next_step_code_landing/images/image69Png.png",
                        fullWidth: 486,
                        fullHeight: 520,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__iuOoN)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__d5ETr
                      )}
                    >
                      {"PUTTING YOUR SUCCESS FIRST"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0VeHa
                      )}
                    >
                      {
                        "We believe that your business deserves a strong, professional online presence. For a single, transparent charge, we design, build, optimize, brand, and write everything you need to succeed in the digital world. Our goal is to exceed your expectations, providing a seamless experience that drives results and long-term growth.\n"
                      }
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.columns__t7Ufu)}>
                  <div
                    className={classNames(projectcss.all, sty.column__axGhH)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__h4OAb
                      )}
                    >
                      {"01   ALL-IN-ONE SOLUTION"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2PTd5
                      )}
                    >
                      {
                        "Your brand\u2019s entire digital identity\u2014designed, developed, optimized and written for you in one package"
                      }
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mEw7L
                      )}
                    >
                      {"02   SIMPLIFIED PRICING"}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fVpeC
                      )}
                    >
                      {
                        "No hidden fees, no surprises. Just $1000 for complete design, development, optimization, branding, and copywriting."
                      }
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section___0LnzK)}>
            <div className={classNames(projectcss.all, sty.columns__vM48T)}>
              <div className={classNames(projectcss.all, sty.column__viPH)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1___9YPy
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#FFFFFF" }}
                    >
                      {"Full package of\n"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#A8FF00" }}
                    >
                      {"Web Solutions for $1000"}
                    </span>
                  </React.Fragment>
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__vFnEa
                  )}
                >
                  {
                    "Get your business online quickly with a custom-built website and ongoing support for growth."
                  }
                </div>
                <div className={classNames(projectcss.all, sty.columns__mef3W)}>
                  <div
                    className={classNames(projectcss.all, sty.column___6OKy9)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.columns___4NHjV
                      )}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__lrJr)}
                      >
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1__thiDs
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#FFFFFF" }}
                            >
                              {"01   DESIGN"}
                            </span>
                          </React.Fragment>
                        </h1>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__az85E
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sd3Q
                          )}
                        >
                          {
                            "Robust and scalable websites built with the latest technologies for optimal performance."
                          }
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__bPqD7)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__hAqAb
                        )}
                      >
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1__e7Rxs
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#FFFFFF" }}
                            >
                              {"02   DEVELOPMENT"}
                            </span>
                          </React.Fragment>
                        </h1>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__w4DBd
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zSjr1
                          )}
                        >
                          {
                            "Robust and scalable websites built with the latest technologies for optimal performance."
                          }
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__bODwW)}
                    >
                      <div
                        className={classNames(projectcss.all, sty.column__hbRj)}
                      >
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1__wvQBz
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#FFFFFF" }}
                            >
                              {"03   OPTIMIZATION"}
                            </span>
                          </React.Fragment>
                        </h1>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__nVy8O
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__dpXeY
                          )}
                        >
                          {
                            "Robust and scalable websites built with the latest technologies for optimal performance."
                          }
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__ntI7K)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ylAeB
                        )}
                      >
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1__dcNkq
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#FFFFFF" }}
                            >
                              {"04   BRANDING"}
                            </span>
                          </React.Fragment>
                        </h1>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__nLBkW
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__saNeb
                          )}
                        >
                          {
                            "Robust and scalable websites built with the latest technologies for optimal performance."
                          }
                        </div>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.columns___0OBop
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__iZzBy
                        )}
                      >
                        <h1
                          className={classNames(
                            projectcss.all,
                            projectcss.h1,
                            projectcss.__wab_text,
                            sty.h1___3SsDy
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ color: "#FFFFFF" }}
                            >
                              {"05   COPYWRITING"}
                            </span>
                          </React.Fragment>
                        </h1>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ugFn1
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uR8Ah
                          )}
                        >
                          {
                            "Crafting compelling, engaging content that communicates your message effectively and drives conversions."
                          }
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.columns__cvz86)}>
                  <div
                    className={classNames(projectcss.all, sty.column__oIviF)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__umXjd
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#FFFFFF" }}
                        >
                          {"Book a call now and get "}
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#A8FF00" }}
                        >
                          {"$50 discount!"}
                        </span>
                      </React.Fragment>
                    </h1>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9P5P7
                      )}
                    >
                      {
                        "We\u2019re excited to help you build a website that not only meets but exceeds your expectations."
                      }
                    </div>
                    <Button
                      className={classNames("__wab_instance", sty.button__dJpk)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___97Ki7
                        )}
                      >
                        {"Book Now"}
                      </div>
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__j0Yog)}>
            <div className={classNames(projectcss.all, sty.columns__kt36)}>
              <div className={classNames(projectcss.all, sty.column__jz2Zr)}>
                <div className={classNames(projectcss.all, sty.columns__oLddy)}>
                  <div
                    className={classNames(projectcss.all, sty.column__xm6SL)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__w2A9G
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#A8FF00" }}
                        >
                          {"Projects "}
                        </span>
                        <React.Fragment>{""}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#DBDED5" }}
                        >
                          {"we"}
                        </span>
                        <React.Fragment>{"\n"}</React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ color: "#DBDED5" }}
                        >
                          {"have completed"}
                        </span>
                      </React.Fragment>
                    </h1>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__jX3Vi)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.columns___9K05K
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__pbvgX
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__xhKTa
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__ldrgh
                            )}
                          >
                            {"Start a Project"}
                          </div>
                        </Button>
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ghj2F
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__tvruo
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__fYuCk
                            )}
                          >
                            {"View More Projects"}
                          </div>
                        </Button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section___0Efzc)}>
            <div className={classNames(projectcss.all, sty.columns__xPo9)}>
              <div className={classNames(projectcss.all, sty.column__yaltF)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__mfI4J
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#FFFFFF" }}
                    >
                      {"What our "}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#A8FF00" }}
                    >
                      {"satisfied client say"}
                    </span>
                  </React.Fragment>
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uWHqs
                  )}
                >
                  {
                    "Get your business online quickly with a custom-built website and ongoing support for growth."
                  }
                </div>
                <div className={classNames(projectcss.all, sty.columns__z830L)}>
                  <div
                    className={classNames(projectcss.all, sty.column___4DX8E)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__sJwUq)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/next_step_code_landing/images/cardPng.png",
                        fullWidth: 1920,
                        fullHeight: 880,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__lOxSr)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__p0VqN)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/next_step_code_landing/images/cardPng.png",
                        fullWidth: 1920,
                        fullHeight: 880,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__aZdFc)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__mt4No)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/next_step_code_landing/images/cardPng.png",
                        fullWidth: 1920,
                        fullHeight: 880,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
                <div className={classNames(projectcss.all, sty.columns__bipnm)}>
                  <div className={classNames(projectcss.all, sty.column__gvGi)}>
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__aoi1Q)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/next_step_code_landing/images/cardPng.png",
                        fullWidth: 1920,
                        fullHeight: 880,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__guEsH)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___08XI)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/next_step_code_landing/images/cardPng.png",
                        fullWidth: 1920,
                        fullHeight: 880,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__bexOq)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___2M4Oe)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/next_step_code_landing/images/cardPng.png",
                        fullWidth: 1920,
                        fullHeight: 880,
                        aspectRatio: undefined
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__eO4R8)}>
            <div className={classNames(projectcss.all, sty.columns__ouNty)}>
              <div className={classNames(projectcss.all, sty.column__pZeec)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__jsmUh)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/next_step_code_landing/images/group3Svg.svg",
                    fullWidth: 1440,
                    fullHeight: 210,
                    aspectRatio: 6.857143
                  }}
                />
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__dhQsu)}>
            <div className={classNames(projectcss.all, sty.columns___8Lx2Z)}>
              <div className={classNames(projectcss.all, sty.column___85LFu)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__qXvs
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#A8FF00" }}
                    >
                      {"Avoid Overwhelming Costs"}
                    </span>
                  </React.Fragment>
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iQcPu
                  )}
                >
                  {
                    "Qorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdu."
                  }
                </div>
                <div className={classNames(projectcss.all, sty.columns__fp4Tb)}>
                  <div
                    className={classNames(projectcss.all, sty.column___0LPa)}
                  >
                    <section
                      className={classNames(projectcss.all, sty.section__sIp5L)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__rm8Z7)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"60px"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/next_step_code_landing/images/webDesign4651372Svg.svg",
                          fullWidth: 56,
                          fullHeight: 56,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vFcvs
                        )}
                      >
                        {"Comprehensive Package"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__aXiSf
                        )}
                      >
                        {
                          "Save significantly with our all-in-one solution. Individually, each service\u2014branding, site design, development, optimization, and copywriting\u2014would cost much more."
                        }
                      </div>
                    </section>
                  </div>
                  <div className={classNames(projectcss.all, sty.column__gfLs)}>
                    <section
                      className={classNames(projectcss.all, sty.section__n1ByG)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img__pjL2)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"60px"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/next_step_code_landing/images/banker12202786Svg.svg",
                          fullWidth: 56,
                          fullHeight: 56,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vj62W
                        )}
                      >
                        {"Freelancer Fees"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gr1Ol
                        )}
                      >
                        {
                          " Skip the hassle and extra expense of hiring multiple freelancers. We handle everything in-house, providing seamless and integrated services.\n"
                        }
                      </div>
                    </section>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__dY1Ch)}
                  >
                    <section
                      className={classNames(projectcss.all, sty.section__xUqGt)}
                    >
                      <PlasmicImg__
                        alt={""}
                        className={classNames(sty.img___82MzO)}
                        displayHeight={"auto"}
                        displayMaxHeight={"none"}
                        displayMaxWidth={"60px"}
                        displayMinHeight={"0"}
                        displayMinWidth={"0"}
                        displayWidth={"100%"}
                        loading={"lazy"}
                        src={{
                          src: "/plasmic/next_step_code_landing/images/monitoring12197909Svg.svg",
                          fullWidth: 56,
                          fullHeight: 56,
                          aspectRatio: 1
                        }}
                      />

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lcvOa
                        )}
                      >
                        {"Hidden Costs"}
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__dPkKh
                        )}
                      >
                        {
                          "Prevent unexpected costs with our transparent pricing. No surprises, just a straightforward fee of $1000 for everything you need."
                        }
                      </div>
                    </section>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section___6GksB)}>
            <div className={classNames(projectcss.all, sty.columns___9IOa)}>
              <div className={classNames(projectcss.all, sty.column__spGtF)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__rwq8C
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#FFFFFF" }}
                    >
                      {"Frequently Asked Questions"}
                    </span>
                  </React.Fragment>
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__shPdG
                  )}
                >
                  {
                    "Get your business online quickly with a custom-built website and ongoing support for growth."
                  }
                </div>
                {(() => {
                  const child$Props = {
                    activeKey: generateStateValueProp($state, [
                      "accordion",
                      "activePanelId"
                    ]),
                    bordered: true,
                    className: classNames("__wab_instance", sty.accordion),
                    items: (
                      <React.Fragment>
                        <AntdAccordionItem
                          className={classNames(
                            "__wab_instance",
                            sty.accordionItem__lzeMt
                          )}
                          id={1}
                          label2={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ynGha
                              )}
                            >
                              {"Nec suscipit curae enim pellentesque"}
                            </div>
                          }
                          showArrow={true}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__xWwwh
                            )}
                          >
                            {"First Children"}
                          </div>
                        </AntdAccordionItem>
                        <AntdAccordionItem
                          className={classNames(
                            "__wab_instance",
                            sty.accordionItem__meXcb
                          )}
                          id={2}
                          label2={
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gmAoB
                              )}
                            >
                              {"Nec suscipit curae enim pellentesque"}
                            </div>
                          }
                          showArrow={true}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__hUa2G
                            )}
                          >
                            {"Second Children"}
                          </div>
                        </AntdAccordionItem>
                      </React.Fragment>
                    ),
                    onChange: async (...eventArgs: any) => {
                      generateStateOnChangePropForCodeComponents(
                        $state,
                        "activePanelId",
                        ["accordion", "activePanelId"],
                        AntdAccordion_Helpers
                      ).apply(null, eventArgs);
                    }
                  };
                  initializeCodeComponentStates(
                    $state,
                    [
                      {
                        name: "activePanelId",
                        plasmicStateName: "accordion.activePanelId"
                      }
                    ],
                    [],
                    AntdAccordion_Helpers ?? {},
                    child$Props
                  );

                  return (
                    <AntdAccordion
                      data-plasmic-name={"accordion"}
                      data-plasmic-override={overrides.accordion}
                      {...child$Props}
                    />
                  );
                })()}
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section___5OfUb)}>
            <div className={classNames(projectcss.all, sty.columns__zl1Yr)}>
              <div className={classNames(projectcss.all, sty.column__ySody)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1___8D0Fi
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>{"Ready to "}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#A8FF00" }}
                    >
                      {"Take Your Website to the Next Step?"}
                    </span>
                  </React.Fragment>
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__tq7Up
                  )}
                >
                  {
                    "We\u2019re excited to help you build a website that not only meets but exceeds your expectations. Book a call with us today and discover how NextStepCode can transform your online presence. Plus, as a special thank you for choosing us, you'll receive a $50 discount on your project!\n\nSchedule Your Free Consultation Now and get $50 discount!"
                  }
                </div>
                <Button
                  className={classNames("__wab_instance", sty.button___7XBlQ)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sMjZq
                    )}
                  >
                    {"Book Now"}
                  </div>
                </Button>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section___9NSmx)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___8CWbC)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__wVach)}
              >
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__ioPqH)}
                  displayHeight={"40px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"233px"}
                  src={{
                    src: "/plasmic/next_step_code_landing/images/group1487663536Svg.svg",
                    fullWidth: 251,
                    fullHeight: 41,
                    aspectRatio: 6.121951
                  }}
                />

                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iLx2)}
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__syp3W)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__pEDfD)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__yRx8)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___60LmY
                      )}
                    >
                      {"Our Story"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__ukTr)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__mkiO6)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__txk2D)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__syRpM
                      )}
                    >
                      {"Projects"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__dz9U)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__p43Y9)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__gsOsM)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bbDep
                      )}
                    >
                      {"Contact"}
                    </div>
                  </Button>
                  <FacebookSvgIcon
                    className={classNames(projectcss.all, sty.svg__eUlbs)}
                    role={"img"}
                  />

                  <InstagramSvgIcon
                    className={classNames(projectcss.all, sty.svg___3Udu)}
                    role={"img"}
                  />

                  <TwitterSvgIcon
                    className={classNames(projectcss.all, sty.svg__ttzU6)}
                    role={"img"}
                  />

                  <LinkedInSvgIcon
                    className={classNames(projectcss.all, sty.svg__j6Od)}
                    role={"img"}
                  />
                </Stack__>
                {false ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__efSK)}
                  >
                    <button
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        projectcss.__wab_text,
                        sty.button___9UUtT
                      )}
                    >
                      {"Sign up"}
                    </button>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__lv1Gu
                      )}
                      color={"clear"}
                      endIcon={
                        <IconIcon
                          className={classNames(projectcss.all, sty.svg__n2T0P)}
                          role={"img"}
                        />
                      }
                      startIcon={
                        <CheckSvgIcon
                          className={classNames(projectcss.all, sty.svg__sv83D)}
                          role={"img"}
                        />
                      }
                      submitsForm={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bDHcu
                        )}
                      >
                        {"Log in"}
                      </div>
                    </Button>
                  </div>
                ) : null}
              </Stack__>
            </Stack__>
            <div className={classNames(projectcss.all, sty.columns__gRxuP)}>
              <div className={classNames(projectcss.all, sty.column__kGrXq)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iksTs
                  )}
                >
                  {"2024 Next Step Code. All rights reserved."}
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__gqJkK)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xOmqI)}
                >
                  <Button
                    className={classNames("__wab_instance", sty.button__yjMpl)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__wfmon)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__rXOkY)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__tGhCo
                      )}
                    >
                      {"Privacy Policy"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__jVdj)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__wlq59)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__neFMb)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__iaPln
                      )}
                    >
                      {"Terms of Service"}
                    </div>
                  </Button>
                  <Button
                    className={classNames("__wab_instance", sty.button__gj4Wr)}
                    color={"clear"}
                    endIcon={
                      <IconIcon
                        className={classNames(projectcss.all, sty.svg__nV4Tw)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__vi5Zg)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dk3Gl
                      )}
                    >
                      {"Legal Disclaimer"}
                    </div>
                  </Button>
                </Stack__>
              </div>
            </div>
          </section>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "accordion"],
  accordion: ["accordion"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  accordion: typeof AntdAccordion;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHomepage__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    accordion: makeNodeComponent("accordion"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
